// Next
import type { Metadata } from "next";
// Next

// CSS
import styles from "./layoutStyles.module.css";
import "./globals.css";
import "react-tooltip/dist/react-tooltip.css";
// CSS

// Components
import Sidebar from "@/Components/Sidebar/Sidebar";
// Components

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="w-full flex flex-row-reverse items-center h-full"
    >
      <body className="flex flex-row-reverse items-center justify-between w-full h-full overflow-hidden">
        <Sidebar />
        <section className={`${styles.masterContianer} w-[calc(100%_-_48px)]`}>
          {children}
        </section>
      </body>
    </html>
  );
}
